# Generated by Django 3.1.3 on 2021-05-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210430_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='menus/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='place',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='places/'),
        ),
        migrations.AddField(
            model_name='review',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant_id',
            field=models.IntegerField(null=True),
        ),
    ]
