# Generated by Django 3.1.3 on 2021-05-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210502_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, default='defaultlogo.jpg', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.ImageField(blank=True, default='defaultmenu.jpg', null=True, upload_to='menus/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='place',
            field=models.ImageField(blank=True, default='defaultplace.jpg', null=True, upload_to='places/'),
        ),
    ]
