# Generated by Django 3.1.3 on 2021-05-04 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_restaurant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
    ]
