# Generated by Django 3.1.3 on 2021-05-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210504_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='review_score',
            field=models.IntegerField(null=True),
        ),
    ]
