# Generated by Django 3.1.3 on 2021-05-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_restaurant_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='review_score',
            field=models.IntegerField(default=4, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='cleanliness',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='environment',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='price',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='taste',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
