# Generated by Django 3.1.3 on 2021-05-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210505_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('choice', models.CharField(default='announcements', max_length=200, null=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
