# Generated by Django 3.1.3 on 2021-05-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='choice',
            field=models.CharField(default='Review Complaint', max_length=200, null=True),
        ),
    ]
