# Generated by Django 3.1.3 on 2021-05-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210506_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='choice',
            field=models.CharField(default='1', max_length=200, null=True),
        ),
    ]
